### ISSUE TITLE
Any progress on this?

### ISSUE THREAD

**Issue by xuv** [theContentMint/GoProRemote#1]
This is super interesting. Have you made any progress since?
I'm in search of a solution to switch cameras in client-mode and set up an AP myself. If you have any clue. Thx.

**Comment by jamiewannenburg** [comment]
Hi xuv, sorry for the late reply.

I have not thought about this in many years and do not own any GoPros at the moment. So, it would be difficult for me to develop this further. But it was a fun project, and I would like to work on it again in the future. Have you tried my code, or the code at https://github.com/joshvillbrandt/GoProController perhaps with newer GoPros?

I do not understand your question. If I remember correctly, when the GoPro is in client mode, it will connect to a remote. The remote will then send commands to all the cameras connected to it and listen to state change messages to confirm that all the GoPros have received the command and has made the appropriate changes. So, in this mode, there is no notion of switching.

Could it be that you mean the other mode? In this mode a GoPro sets up its own wifi network, which you can connect to with a client. The link above was intended to hack that mode, and it was even able switch between different GoPros by connecting to their respective networks one at a time.

There might have been structural changes to how all this works in newer GoPros. Do you know if this is the case? Furthermore, if you want to take ownership of this project, that can be arranged.

**Comment by xuv** [comment]
Thanks for the reply. Indeed, my question is maybe not clear. I was looking for a way to spoof the remote. As you say, cameras set themselves in client mode when connected to a remote. I'm looking for a way to use a computer as a remote and control multiple cameras at the same time.

**Comment by jamiewannenburg** [comment]
The discussion in https://github.com/theContentMint/GoProRemote/issues/2 might be usefull to you. Esspacially the issue noted by KonradIT.

**Comment by xuv** [comment]
Thx.
